-- AI-RTS schema (repo-scoped test history)

CREATE TABLE test_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id VARCHAR(255) NOT NULL,
    test_id VARCHAR(512) NOT NULL,
    result VARCHAR(32) NOT NULL,
    duration BIGINT NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    pr_id VARCHAR(128) NOT NULL
);

CREATE INDEX idx_test_runs_repo_ts ON test_runs (repo_id, timestamp);
CREATE INDEX idx_test_runs_repo_test ON test_runs (repo_id, test_id);

CREATE TABLE test_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id VARCHAR(255) NOT NULL,
    class_name VARCHAR(512) NOT NULL,
    method_name VARCHAR(256) NOT NULL,
    tags VARCHAR(512),
    type VARCHAR(64),
    avg_duration BIGINT NOT NULL,
    CONSTRAINT uq_test_metadata_repo_class_method UNIQUE (repo_id, class_name, method_name)
);

CREATE INDEX idx_test_metadata_repo ON test_metadata (repo_id);

CREATE TABLE code_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path VARCHAR(1024) NOT NULL,
    lines_added INT NOT NULL,
    lines_removed INT NOT NULL,
    methods_touched VARCHAR(2048)
);
